SELECT name, RANDOM() FROM tracks;

SELECT name, RANDOM() FROM tracks
ORDER BY RANDOM()
LIMIT 10;

SELECT name, RANDOM() FROM tracks
ORDER BY RANDOM() DESC
LIMIT 10;

SELECT name FROM tracks
ORDER BY RANDOM() DESC
LIMIT 10;
